displayName=Equipment Check
author=andyli2005
description=Alerts you when you have nothing equipped in gear slots
tags=hint,gear,head
version=
plugins=com.equipmentcheck.EquipmentCheckPlugin
build=standard