displayName=Equipment Check
author=andyli2005
description=Alerts you when a gear slot is empty or missing a specific item
tags=hint,gear,equipment,item
version=
plugins=com.equipmentcheck.EquipmentCheckPlugin
build=standard