displayName=Helmet check
author=andyli2005
description=Alerts you when you have nothing equipped in your head slot
tags=hint,gear,head
version=
plugins=com.helmetcheck.HelmetCheckPlugin
build=standard